---
title: "Coffee Break Experiment #2"
author: "Sam Kalman and Charles Hutchinson"
date: "2022-11-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = F}
# Load Package
library(syuzhet)
library(tidyverse)
library(SentimentAnalysis)
library(ggridges)
```

```{r}
# Load and Join Bay Area Fire Tweets

# 4680 Tweets by 7 Variables
bay_area_tweets <- readRDS("bay_area_tweets.RDS")
# 3807 Users by 8 Variables
bay_area_users <- readRDS("bay_area_users.RDS")
colnames(bay_area_users)[1] <- "author_id"

# 3294 Unique Users
bay_area_users <- bay_area_users %>% 
  group_by(author_id) %>% 
  summarize_all(max)

# Join into one table
bay <- inner_join(bay_area_tweets, bay_area_users, by = "author_id") %>%
  mutate(fire = "Bay Area Fire")
```

```{r}
# Load and Join Camp Fire Tweets

# 50469 Tweets by 7 Variables
camp_tweets <- readRDS("camp_tweets.RDS")
# 44376 Users by 8 Variables
camp_users <- readRDS("camp_users.RDS")
colnames(camp_users)[1] <- "author_id"

# 26353 Unique Users
camp_users <- camp_users %>% 
  group_by(author_id) %>% 
  summarize_all(max)

# Join into one table
camp <- inner_join(camp_tweets, camp_users, by = "author_id") %>%
  mutate(fire = "Camp Fire")
```

```{r}
# Load and Join Dixie Fire Tweets

# 26139 Tweets by 7 Variables
dixie_tweets <- readRDS("dixie_tweets.RDS")
# 21230 Users by 8 Variables
dixie_users <- readRDS("dixie_users.RDS")
colnames(dixie_users)[1] <- "author_id"

# 11438 Unique Users
dixie_users <- dixie_users %>% 
  group_by(author_id) %>% 
  summarize_all(max)

# Join into one table
dixie <- inner_join(dixie_tweets, dixie_users, by = "author_id") %>%
  mutate(fire = "Dixie Fire")
```

```{r}
# Load and Join Tubbs Fire Tweets

# 3530 Tweets by 7 Variables
tubbs_tweets <- readRDS("tubbs_tweets.RDS")
# 2826 Users by 8 Variables
tubbs_users <- readRDS("tubbs_users.RDS")
colnames(tubbs_users)[1] <- "author_id"

# 2334 Unique Users
tubbs_users <- tubbs_users %>% 
  group_by(author_id) %>% 
  summarize_all(max)

# Join into one table
tubbs <- inner_join(tubbs_tweets, tubbs_users, by = "author_id") %>%
  mutate(fire = "Tubbs Fire")
```

```{r}
# Create Main Data Frame
main <- rbind(bay, camp, dixie, tubbs)
```

```{r}
# Pre-Processing
## Remove links and websites
main$text <- gsub("https.*","",main$text)
main$text <- gsub("http.*","",main$text)
main$text <- gsub("www.*","",main$text)
## Remove Twitter Handles
main$text <- gsub("@([a-zA-Z0-9]|[_])*","",main$text)

## Note: May need to add other pre-processing steps
```

```{r}
# Run Sentiment from syuzhet package
syuzhet_df <- get_sentiment(main$text) %>% as.data.frame()
```

```{r}
# Run Sentiment from SentimentAnalysis package
### Took 20ish minutes to run ###
analyzeSent_df <- analyzeSentiment(main$text)
```

```{r}
# Combine Sentiment Scores from both methods in main dataframe
main <- cbind(main, syuzhet_df, analyzeSent_df["SentimentQDAP"])
colnames(main)[16:17] <- c("syuzhet","SentimentAnalysis")
```

```{r}
# Save DataFrame as CSV
write.csv(main, "MainSentiment.csv", row.names = FALSE)
```

```{r}
# Syuzhet Range: -7.10 to 6.35
# SentimentAnalysis Range: -1 to 1
# > 0 is Positive for Both
# < 0 is Negative for Both
```

```{r}
# Add binary Positive and Negative values for both methods
main <- main %>% 
  mutate(syuzScore = case_when(syuzhet > 0 ~ "Positive", 
                               syuzhet < 0 ~ "Negative",
                               syuzhet == 0 ~ "Neutral"),
         saScore = case_when(SentimentAnalysis > 0 ~ "Positive", 
                             SentimentAnalysis < 0 ~ "Negative",
                             SentimentAnalysis == 0 ~ "Neutral"))


```

**Use Syuzhet Metric **

```{r}
 main %>%
  filter(followers_count > 0 & following_count > 0 & like_count > 0 & retweet_count > 0) %>%
  mutate(fire = fct_relevel(fire, c("Tubbs Fire", 
                      "Camp Fire", 
                      "Bay Area Fire", 
                      "Dixie Fire"))) %>%
  group_by(fire) %>%
  summarize(positive = length(syuzScore[syuzScore == "Positive"]) / n(),
            negative = length(syuzScore[syuzScore == "Negative"]) / n(),
            neutral = length(syuzScore[syuzScore == "Neutral"]) / n()) %>%
  gather(sentiment, percentage, positive:neutral) %>%
  ggplot(aes(x = fire, y = percentage, fill = sentiment)) +
  geom_bar(stat = "identity", position = "dodge") + 
  scale_fill_manual(values = c("red2", "blue", "darkgreen")) +
  theme_bw()
```

```{r}
# Remove News Organizations
 main %>%
  filter(followers_count > 0 & following_count > 0 & like_count > 0 & retweet_count > 0 & reply_count > 0) %>%
  filter(!stringr::str_detect(description,'news|meteorology')) %>%
  mutate(fire = fct_relevel(fire, c("Tubbs Fire", 
                      "Camp Fire", 
                      "Bay Area Fire", 
                      "Dixie Fire"))) %>%
  group_by(fire) %>%
  summarize(positive = length(syuzScore[syuzScore == "Positive"]) / n(),
            negative = length(syuzScore[syuzScore == "Negative"]) / n(),
            neutral = length(syuzScore[syuzScore == "Neutral"]) / n()) %>%
  gather(sentiment, percentage, positive:neutral) %>%
  ggplot(aes(x = fire, y = percentage, fill = sentiment)) +
  geom_bar(stat = "identity", position = "dodge") + 
  scale_fill_manual(values = c("red2", "blue", "darkgreen")) + 
  theme_bw()
```

```{r}
main %>%
  filter(followers_count > 0 & following_count > 0 & like_count > 0 & retweet_count > 0) %>%
  mutate(fire = fct_relevel(fire, c("Tubbs Fire", 
                      "Camp Fire", 
                      "Bay Area Fire", 
                      "Dixie Fire"))) %>%
  ggplot(aes(x = syuzhet)) +
  geom_density(stat = "density") +
  facet_wrap(~fire, ncol = 1) +
  theme_bw()
```

**Use SentimentAnalysis Metric**

```{r}
 main %>%
  mutate(fire = fct_relevel(fire, c("Tubbs Fire", 
                      "Camp Fire", 
                      "Bay Area Fire", 
                      "Dixie Fire"))) %>%
  group_by(fire) %>%
  summarize(positive = length(saScore[saScore == "Positive"]) / n(),
            negative = length(saScore[saScore == "Negative"]) / n(),
            neutral = length(saScore[saScore == "Neutral"]) / n()) %>%
  gather(sentiment, percentage, positive:neutral) %>%
  ggplot(aes(x = fire, y = percentage, fill = sentiment)) +
  geom_bar(stat = "identity", position = "dodge") + 
  theme_bw()
```

```{r}
# Remove News Organizations
 main %>%
  filter(!stringr::str_detect(description,'news|meteorology')) %>%
  mutate(fire = fct_relevel(fire, c("Tubbs Fire", 
                      "Camp Fire", 
                      "Bay Area Fire", 
                      "Dixie Fire"))) %>%
  group_by(fire) %>%
  summarize(positive = length(saScore[saScore == "Positive"]) / n(),
            negative = length(saScore[saScore == "Negative"]) / n(),
            neutral = length(saScore[saScore == "Neutral"]) / n()) %>%
  gather(sentiment, percentage, positive:neutral) %>%
  ggplot(aes(x = fire, y = percentage, fill = sentiment)) +
  geom_bar(stat = "identity", position = "dodge") + 
  theme_bw()
```

```{r}
main %>%
  mutate(fire = fct_relevel(fire, c("Tubbs Fire", 
                      "Camp Fire", 
                      "Bay Area Fire", 
                      "Dixie Fire"))) %>%
  ggplot(aes(x = SentimentAnalysis)) +
  geom_density(stat = "density") +
  facet_wrap(~fire, ncol = 1) +
  theme_bw()
```